namespace Application.Modules.R2Y.Models;

public record AuthUserClaims
{
    public int? IdMR { get; set; }
    public string? Pais { get; set; }
    public string? Moeda { get; set; }
    public string? Email { get; set; }
    public string? Id { get; set; }
    public string? FullName { get; set; }
    public string? Perfil { get; set; }
    public string? MPerfil { get; set; }
    public string? IdRegiao { get; set; }
    public string? GuidRegion { get; set; }
    public string? Idc { get; set; }
    public string? MDirector { get; set; }
    public bool IsMember { get; set; }
    public string MemberGroup { get; set; }
    public bool MemberDashBoardLT { get; set; }
    public bool MemberDashBoardMC { get; set; }
    public bool IsMemberVerified { get; set; }
    public bool IsMemberAutoGenerated { get; set; }
    public long TlmId { get; set; }
    
    public bool MemberLogin { get; set; }
    public string MemberRole { get; set; }
    public string DefaultLanguange { get; set; }
    public string ImageUrl { get; set; }
    public string MemberCountry { get; set; }
    public string MemberIdRegion { get; set; }

}