using System.Security.Claims;
using Application.Modules.R2Y.Models;

namespace Application.Extensions;

public static class ExtractClaimsPrincipal
{
       public static AuthUserClaims? ToUserModel(this ClaimsPrincipal? principal)
    {
        if (principal?.Identity?.IsAuthenticated != true)
            return null;

        var claims = principal.Claims
            .GroupBy(c => c.Type, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.Last().Value, StringComparer.OrdinalIgnoreCase);

        return new AuthUserClaims
        {
            IdMR = GetInt("IdMR"),
            Id = Get(ClaimTypes.NameIdentifier),
            Email = Get(ClaimTypes.Email),
            Perfil = GetKey("Perfil"),
            FullName = GetKey("FullName"),
            MPerfil = GetKey("mPerfil"),
            IdRegiao = GetKey("IdRegion"),
            GuidRegion = GetKey("GuidRegion"),
            Idc = GetKey("IdC"),
            IsMember = GetBool("IsMember"),
            Pais = GetKey("Country"),
            Moeda = GetKey("Currency"),
            MemberDashBoardLT = GetBool("MemberDashBoardLT"),
            MemberDashBoardMC = GetBool("MemberDashBoardMC"),
            IsMemberVerified = GetBool("IsMemberVerified"),
            IsMemberAutoGenerated = GetBool("IsMemberAutoGenerated"),
            TlmId = GetLong("tlmId"),
            MemberGroup = GetKey("MemberGroup"),
            MemberRole = GetKey("MemberRole"),
            DefaultLanguange = GetKey("defaultLanguage"),
            ImageUrl = GetKey("ImageUrl"),
            MemberCountry = GetKey("MemberCountry"),
            MemberIdRegion = GetKey("MemberIdRegion")
        };

        string Get(string type) =>
            principal.FindFirst(type)?.Value ?? string.Empty;

        string GetKey(string key) =>
            claims.TryGetValue(key, out var v) ? v : string.Empty;

        bool GetBool(string key) =>
            claims.TryGetValue(key, out var v) && bool.TryParse(v, out var b) && b;

        long GetLong(string key) =>
            claims.TryGetValue(key, out var v) && long.TryParse(v, out var n) ? n : 0L;
        
        int GetInt(string key) =>
            claims.TryGetValue(key, out var v) && int.TryParse(v, out var n) ? n : 0;
    }
}